package com.avinash.whatsthetime.dataclass

import kotlinx.datetime.TimeZone

data class Cites(val name: String, val timeZoneId: TimeZone)

val cites = listOf(
    Cites("Abidjan", TimeZone.of("Africa/Abidjan")),
    Cites("Accra", TimeZone.of("Africa/Accra")),
    Cites("Addis Ababa", TimeZone.of("Africa/Addis_Ababa")),
    Cites("Algiers", TimeZone.of("Africa/Algiers")),
    Cites("Asmara", TimeZone.of("Africa/Asmara")),
    Cites("Asmera", TimeZone.of("Africa/Asmera")),
    Cites("Bamako", TimeZone.of("Africa/Bamako")),
    Cites("Bangui", TimeZone.of("Africa/Bangui")),
    Cites("Banjul", TimeZone.of("Africa/Banjul")),
    Cites("Bissau", TimeZone.of("Africa/Bissau")),
    Cites("Blantyre", TimeZone.of("Africa/Blantyre")),
    Cites("Brazzaville", TimeZone.of("Africa/Brazzaville")),
    Cites("Bujumbura", TimeZone.of("Africa/Bujumbura")),
    Cites("Cairo", TimeZone.of("Africa/Cairo")),
    Cites("Casablanca", TimeZone.of("Africa/Casablanca")),
    Cites("Ceuta", TimeZone.of("Africa/Ceuta")),
    Cites("Conakry", TimeZone.of("Africa/Conakry")),
    Cites("Dakar", TimeZone.of("Africa/Dakar")),
    Cites("Dar es Salaam", TimeZone.of("Africa/Dar_es_Salaam")),
    Cites("Djibouti", TimeZone.of("Africa/Djibouti")),
    Cites("Douala", TimeZone.of("Africa/Douala")),
    Cites("El Aaiun", TimeZone.of("Africa/El_Aaiun")),
    Cites("Freetown", TimeZone.of("Africa/Freetown")),
    Cites("Gaborone", TimeZone.of("Africa/Gaborone")),
    Cites("Harare", TimeZone.of("Africa/Harare")),
    Cites("Johannesburg", TimeZone.of("Africa/Johannesburg")),
    Cites("Juba", TimeZone.of("Africa/Juba")),
    Cites("Kampala", TimeZone.of("Africa/Kampala")),
    Cites("Khartoum", TimeZone.of("Africa/Khartoum")),
    Cites("Kigali", TimeZone.of("Africa/Kigali")),
    Cites("Kinshasa", TimeZone.of("Africa/Kinshasa")),
    Cites("Lagos", TimeZone.of("Africa/Lagos")),
    Cites("Libreville", TimeZone.of("Africa/Libreville")),
    Cites("Lome", TimeZone.of("Africa/Lome")),
    Cites("Luanda", TimeZone.of("Africa/Luanda")),
    Cites("Lubumbashi", TimeZone.of("Africa/Lubumbashi")),
    Cites("Lusaka", TimeZone.of("Africa/Lusaka")),
    Cites("Malabo", TimeZone.of("Africa/Malabo")),
    Cites("Maputo", TimeZone.of("Africa/Maputo")),
    Cites("Maseru", TimeZone.of("Africa/Maseru")),
    Cites("Mbabane", TimeZone.of("Africa/Mbabane")),
    Cites("Mogadishu", TimeZone.of("Africa/Mogadishu")),
    Cites("Monrovia", TimeZone.of("Africa/Monrovia")),
    Cites("Nairobi", TimeZone.of("Africa/Nairobi")),
    Cites("Ndjamena", TimeZone.of("Africa/Ndjamena")),
    Cites("Niamey", TimeZone.of("Africa/Niamey")),
    Cites("Nouakchott", TimeZone.of("Africa/Nouakchott")),
    Cites("Ouagadougou", TimeZone.of("Africa/Ouagadougou")),
    Cites("Porto-Novo", TimeZone.of("Africa/Porto-Novo")),
    Cites("Sao Tome", TimeZone.of("Africa/Sao_Tome")),
    Cites("Timbuktu", TimeZone.of("Africa/Timbuktu")),
    Cites("Tripoli", TimeZone.of("Africa/Tripoli")),
    Cites("Tunis", TimeZone.of("Africa/Tunis")),
    Cites("Windhoek", TimeZone.of("Africa/Windhoek")),
    Cites("Adak", TimeZone.of("America/Adak")),
    Cites("Anchorage", TimeZone.of("America/Anchorage")),
    Cites("Anguilla", TimeZone.of("America/Anguilla")),
    Cites("Antigua", TimeZone.of("America/Antigua")),
    Cites("Araguaina", TimeZone.of("America/Araguaina")),
    Cites("Argentina", TimeZone.of("America/Argentina/Buenos_Aires")),
    Cites("Argentina", TimeZone.of("America/Argentina/Catamarca")),
    Cites("Argentina", TimeZone.of("America/Argentina/ComodRivadavia")),
    Cites("Argentina", TimeZone.of("America/Argentina/Cordoba")),
    Cites("Argentina", TimeZone.of("America/Argentina/Jujuy")),
    Cites("Argentina", TimeZone.of("America/Argentina/La_Rioja")),
    Cites("Argentina", TimeZone.of("America/Argentina/Mendoza")),
    Cites("Argentina", TimeZone.of("America/Argentina/Rio_Gallegos")),
    Cites("Argentina", TimeZone.of("America/Argentina/Salta")),
    Cites("Argentina", TimeZone.of("America/Argentina/San_Juan")),
    Cites("Argentina", TimeZone.of("America/Argentina/San_Luis")),
    Cites("Argentina", TimeZone.of("America/Argentina/Tucuman")),
    Cites("Argentina", TimeZone.of("America/Argentina/Ushuaia")),
    Cites("Aruba", TimeZone.of("America/Aruba")),
    Cites("Asuncion", TimeZone.of("America/Asuncion")),
    Cites("Atikokan", TimeZone.of("America/Atikokan")),
    Cites("Atka", TimeZone.of("America/Atka")),
    Cites("Bahia", TimeZone.of("America/Bahia")),
    Cites("Bahia Banderas", TimeZone.of("America/Bahia_Banderas")),
    Cites("Barbados", TimeZone.of("America/Barbados")),
    Cites("Belem", TimeZone.of("America/Belem")),
    Cites("Belize", TimeZone.of("America/Belize")),
    Cites("Blanc-Sablon", TimeZone.of("America/Blanc-Sablon")),
    Cites("Boa Vista", TimeZone.of("America/Boa_Vista")),
    Cites("Bogota", TimeZone.of("America/Bogota")),
    Cites("Boise", TimeZone.of("America/Boise")),
    Cites("Buenos Aires", TimeZone.of("America/Buenos_Aires")),
    Cites("Cambridge Bay", TimeZone.of("America/Cambridge_Bay")),
    Cites("Campo Grande", TimeZone.of("America/Campo_Grande")),
    Cites("Cancun", TimeZone.of("America/Cancun")),
    Cites("Caracas", TimeZone.of("America/Caracas")),
    Cites("Catamarca", TimeZone.of("America/Catamarca")),
    Cites("Cayenne", TimeZone.of("America/Cayenne")),
    Cites("Cayman", TimeZone.of("America/Cayman")),
    Cites("Chicago", TimeZone.of("America/Chicago")),
    Cites("Chihuahua", TimeZone.of("America/Chihuahua")),
    Cites("Ciudad Juarez", TimeZone.of("America/Ciudad_Juarez")),
    Cites("Coral Harbour", TimeZone.of("America/Coral_Harbour")),
    Cites("Cordoba", TimeZone.of("America/Cordoba")),
    Cites("Costa Rica", TimeZone.of("America/Costa_Rica")),
    Cites("Creston", TimeZone.of("America/Creston")),
    Cites("Cuiaba", TimeZone.of("America/Cuiaba")),
    Cites("Curacao", TimeZone.of("America/Curacao")),
    Cites("Danmarkshavn", TimeZone.of("America/Danmarkshavn")),
    Cites("Dawson", TimeZone.of("America/Dawson")),
    Cites("Dawson Creek", TimeZone.of("America/Dawson_Creek")),
    Cites("Denver", TimeZone.of("America/Denver")),
    Cites("Detroit", TimeZone.of("America/Detroit")),
    Cites("Dominica", TimeZone.of("America/Dominica")),
    Cites("Edmonton", TimeZone.of("America/Edmonton")),
    Cites("Eirunepe", TimeZone.of("America/Eirunepe")),
    Cites("El Salvador", TimeZone.of("America/El_Salvador")),
    Cites("Ensenada", TimeZone.of("America/Ensenada")),
    Cites("Fort Nelson", TimeZone.of("America/Fort_Nelson")),
    Cites("Fort Wayne", TimeZone.of("America/Fort_Wayne")),
    Cites("Fortaleza", TimeZone.of("America/Fortaleza")),
    Cites("Glace Bay", TimeZone.of("America/Glace_Bay")),
    Cites("Godthab", TimeZone.of("America/Godthab")),
    Cites("Goose Bay", TimeZone.of("America/Goose_Bay")),
    Cites("Grand Turk", TimeZone.of("America/Grand_Turk")),
    Cites("Grenada", TimeZone.of("America/Grenada")),
    Cites("Guadeloupe", TimeZone.of("America/Guadeloupe")),
    Cites("Guatemala", TimeZone.of("America/Guatemala")),
    Cites("Guayaquil", TimeZone.of("America/Guayaquil")),
    Cites("Guyana", TimeZone.of("America/Guyana")),
    Cites("Halifax", TimeZone.of("America/Halifax")),
    Cites("Havana", TimeZone.of("America/Havana")),
    Cites("Hermosillo", TimeZone.of("America/Hermosillo")),
    Cites("Indiana", TimeZone.of("America/Indiana/Indianapolis")),
    Cites("Indiana", TimeZone.of("America/Indiana/Knox")),
    Cites("Indiana", TimeZone.of("America/Indiana/Marengo")),
    Cites("Indiana", TimeZone.of("America/Indiana/Petersburg")),
    Cites("Indiana", TimeZone.of("America/Indiana/Tell_City")),
    Cites("Indiana", TimeZone.of("America/Indiana/Vevay")),
    Cites("Indiana", TimeZone.of("America/Indiana/Vincennes")),
    Cites("Indiana", TimeZone.of("America/Indiana/Winamac")),
    Cites("Indianapolis", TimeZone.of("America/Indianapolis")),
    Cites("Inuvik", TimeZone.of("America/Inuvik")),
    Cites("Iqaluit", TimeZone.of("America/Iqaluit")),
    Cites("Jamaica", TimeZone.of("America/Jamaica")),
    Cites("Jujuy", TimeZone.of("America/Jujuy")),
    Cites("Juneau", TimeZone.of("America/Juneau")),
    Cites("Kentucky", TimeZone.of("America/Kentucky/Louisville")),
    Cites("Kentucky", TimeZone.of("America/Kentucky/Monticello")),
    Cites("Knox IN", TimeZone.of("America/Knox_IN")),
    Cites("Kralendijk", TimeZone.of("America/Kralendijk")),
    Cites("La Paz", TimeZone.of("America/La_Paz")),
    Cites("Lima", TimeZone.of("America/Lima")),
    Cites("Los Angeles", TimeZone.of("America/Los_Angeles")),
    Cites("Louisville", TimeZone.of("America/Louisville")),
    Cites("Lower Princes", TimeZone.of("America/Lower_Princes")),
    Cites("Maceio", TimeZone.of("America/Maceio")),
    Cites("Managua", TimeZone.of("America/Managua")),
    Cites("Manaus", TimeZone.of("America/Manaus")),
    Cites("Marigot", TimeZone.of("America/Marigot")),
    Cites("Martinique", TimeZone.of("America/Martinique")),
    Cites("Matamoros", TimeZone.of("America/Matamoros")),
    Cites("Mazatlan", TimeZone.of("America/Mazatlan")),
    Cites("Mendoza", TimeZone.of("America/Mendoza")),
    Cites("Menominee", TimeZone.of("America/Menominee")),
    Cites("Merida", TimeZone.of("America/Merida")),
    Cites("Metlakatla", TimeZone.of("America/Metlakatla")),
    Cites("Mexico City", TimeZone.of("America/Mexico_City")),
    Cites("Miquelon", TimeZone.of("America/Miquelon")),
    Cites("Moncton", TimeZone.of("America/Moncton")),
    Cites("Monterrey", TimeZone.of("America/Monterrey")),
    Cites("Montevideo", TimeZone.of("America/Montevideo")),
    Cites("Montreal", TimeZone.of("America/Montreal")),
    Cites("Montserrat", TimeZone.of("America/Montserrat")),
    Cites("Nassau", TimeZone.of("America/Nassau")),
    Cites("New York", TimeZone.of("America/New_York")),
    Cites("Nipigon", TimeZone.of("America/Nipigon")),
    Cites("Nome", TimeZone.of("America/Nome")),
    Cites("Noronha", TimeZone.of("America/Noronha")),
    Cites("North Dakota", TimeZone.of("America/North_Dakota/Beulah")),
    Cites("North Dakota", TimeZone.of("America/North_Dakota/Center")),
    Cites("North Dakota", TimeZone.of("America/North_Dakota/New_Salem")),
    Cites("Nuuk", TimeZone.of("America/Nuuk")),
    Cites("Ojinaga", TimeZone.of("America/Ojinaga")),
    Cites("Panama", TimeZone.of("America/Panama")),
    Cites("Pangnirtung", TimeZone.of("America/Pangnirtung")),
    Cites("Paramaribo", TimeZone.of("America/Paramaribo")),
    Cites("Phoenix", TimeZone.of("America/Phoenix")),
    Cites("Port-au-Prince", TimeZone.of("America/Port-au-Prince")),
    Cites("Port of Spain", TimeZone.of("America/Port_of_Spain")),
    Cites("Porto Acre", TimeZone.of("America/Porto_Acre")),
    Cites("Porto Velho", TimeZone.of("America/Porto_Velho")),
    Cites("Puerto Rico", TimeZone.of("America/Puerto_Rico")),
    Cites("Punta Arenas", TimeZone.of("America/Punta_Arenas")),
    Cites("Rainy River", TimeZone.of("America/Rainy_River")),
    Cites("Rankin Inlet", TimeZone.of("America/Rankin_Inlet")),
    Cites("Recife", TimeZone.of("America/Recife")),
    Cites("Regina", TimeZone.of("America/Regina")),
    Cites("Resolute", TimeZone.of("America/Resolute")),
    Cites("Rio Branco", TimeZone.of("America/Rio_Branco")),
    Cites("Rosario", TimeZone.of("America/Rosario")),
    Cites("Santa Isabel", TimeZone.of("America/Santa_Isabel")),
    Cites("Santarem", TimeZone.of("America/Santarem")),
    Cites("Santiago", TimeZone.of("America/Santiago")),
    Cites("Santo Domingo", TimeZone.of("America/Santo_Domingo")),
    Cites("Sao Paulo", TimeZone.of("America/Sao_Paulo")),
    Cites("Scoresbysund", TimeZone.of("America/Scoresbysund")),
    Cites("Shiprock", TimeZone.of("America/Shiprock")),
    Cites("Sitka", TimeZone.of("America/Sitka")),
    Cites("St Barthelemy", TimeZone.of("America/St_Barthelemy")),
    Cites("St Johns", TimeZone.of("America/St_Johns")),
    Cites("St Kitts", TimeZone.of("America/St_Kitts")),
    Cites("St Lucia", TimeZone.of("America/St_Lucia")),
    Cites("St Thomas", TimeZone.of("America/St_Thomas")),
    Cites("St Vincent", TimeZone.of("America/St_Vincent")),
    Cites("Swift Current", TimeZone.of("America/Swift_Current")),
    Cites("Tegucigalpa", TimeZone.of("America/Tegucigalpa")),
    Cites("Thule", TimeZone.of("America/Thule")),
    Cites("Thunder Bay", TimeZone.of("America/Thunder_Bay")),
    Cites("Tijuana", TimeZone.of("America/Tijuana")),
    Cites("Toronto", TimeZone.of("America/Toronto")),
    Cites("Tortola", TimeZone.of("America/Tortola")),
    Cites("Vancouver", TimeZone.of("America/Vancouver")),
    Cites("Virgin", TimeZone.of("America/Virgin")),
    Cites("Whitehorse", TimeZone.of("America/Whitehorse")),
    Cites("Winnipeg", TimeZone.of("America/Winnipeg")),
    Cites("Yakutat", TimeZone.of("America/Yakutat")),
    Cites("Yellowknife", TimeZone.of("America/Yellowknife")),
    Cites("Casey", TimeZone.of("Antarctica/Casey")),
    Cites("Davis", TimeZone.of("Antarctica/Davis")),
    Cites("DumontDUrville", TimeZone.of("Antarctica/DumontDUrville")),
    Cites("Macquarie", TimeZone.of("Antarctica/Macquarie")),
    Cites("Mawson", TimeZone.of("Antarctica/Mawson")),
    Cites("McMurdo", TimeZone.of("Antarctica/McMurdo")),
    Cites("Palmer", TimeZone.of("Antarctica/Palmer")),
    Cites("Rothera", TimeZone.of("Antarctica/Rothera")),
    Cites("South Pole", TimeZone.of("Antarctica/South_Pole")),
    Cites("Syowa", TimeZone.of("Antarctica/Syowa")),
    Cites("Troll", TimeZone.of("Antarctica/Troll")),
    Cites("Vostok", TimeZone.of("Antarctica/Vostok")),
    Cites("Longyearbyen", TimeZone.of("Arctic/Longyearbyen")),
    Cites("Aden", TimeZone.of("Asia/Aden")),
    Cites("Almaty", TimeZone.of("Asia/Almaty")),
    Cites("Amman", TimeZone.of("Asia/Amman")),
    Cites("Anadyr", TimeZone.of("Asia/Anadyr")),
    Cites("Aqtau", TimeZone.of("Asia/Aqtau")),
    Cites("Aqtobe", TimeZone.of("Asia/Aqtobe")),
    Cites("Ashgabat", TimeZone.of("Asia/Ashgabat")),
    Cites("Ashkhabad", TimeZone.of("Asia/Ashkhabad")),
    Cites("Atyrau", TimeZone.of("Asia/Atyrau")),
    Cites("Baghdad", TimeZone.of("Asia/Baghdad")),
    Cites("Bahrain", TimeZone.of("Asia/Bahrain")),
    Cites("Baku", TimeZone.of("Asia/Baku")),
    Cites("Bangkok", TimeZone.of("Asia/Bangkok")),
    Cites("Barnaul", TimeZone.of("Asia/Barnaul")),
    Cites("Beirut", TimeZone.of("Asia/Beirut")),
    Cites("Bishkek", TimeZone.of("Asia/Bishkek")),
    Cites("Brunei", TimeZone.of("Asia/Brunei")),
    Cites("Calcutta", TimeZone.of("Asia/Calcutta")),
    Cites("Chita", TimeZone.of("Asia/Chita")),
    Cites("Choibalsan", TimeZone.of("Asia/Choibalsan")),
    Cites("Chongqing", TimeZone.of("Asia/Chongqing")),
    Cites("Chungking", TimeZone.of("Asia/Chungking")),
    Cites("Colombo", TimeZone.of("Asia/Colombo")),
    Cites("Dacca", TimeZone.of("Asia/Dacca")),
    Cites("Damascus", TimeZone.of("Asia/Damascus")),
    Cites("Dhaka", TimeZone.of("Asia/Dhaka")),
    Cites("Dili", TimeZone.of("Asia/Dili")),
    Cites("Dubai", TimeZone.of("Asia/Dubai")),
    Cites("Dushanbe", TimeZone.of("Asia/Dushanbe")),
    Cites("Famagusta", TimeZone.of("Asia/Famagusta")),
    Cites("Gaza", TimeZone.of("Asia/Gaza")),
    Cites("Harbin", TimeZone.of("Asia/Harbin")),
    Cites("Hebron", TimeZone.of("Asia/Hebron")),
    Cites("Ho Chi Minh", TimeZone.of("Asia/Ho_Chi_Minh")),
    Cites("Hong Kong", TimeZone.of("Asia/Hong_Kong")),
    Cites("Hovd", TimeZone.of("Asia/Hovd")),
    Cites("Irkutsk", TimeZone.of("Asia/Irkutsk")),
    Cites("Istanbul", TimeZone.of("Asia/Istanbul")),
    Cites("Jakarta", TimeZone.of("Asia/Jakarta")),
    Cites("Jayapura", TimeZone.of("Asia/Jayapura")),
    Cites("Jerusalem", TimeZone.of("Asia/Jerusalem")),
    Cites("Kabul", TimeZone.of("Asia/Kabul")),
    Cites("Kamchatka", TimeZone.of("Asia/Kamchatka")),
    Cites("Karachi", TimeZone.of("Asia/Karachi")),
    Cites("Kashgar", TimeZone.of("Asia/Kashgar")),
    Cites("Kathmandu", TimeZone.of("Asia/Kathmandu")),
    Cites("Katmandu", TimeZone.of("Asia/Katmandu")),
    Cites("Khandyga", TimeZone.of("Asia/Khandyga")),
    Cites("Kolkata", TimeZone.of("Asia/Kolkata")),
    Cites("Krasnoyarsk", TimeZone.of("Asia/Krasnoyarsk")),
    Cites("Kuala Lumpur", TimeZone.of("Asia/Kuala_Lumpur")),
    Cites("Kuching", TimeZone.of("Asia/Kuching")),
    Cites("Kuwait", TimeZone.of("Asia/Kuwait")),
    Cites("Macao", TimeZone.of("Asia/Macao")),
    Cites("Macau", TimeZone.of("Asia/Macau")),
    Cites("Magadan", TimeZone.of("Asia/Magadan")),
    Cites("Makassar", TimeZone.of("Asia/Makassar")),
    Cites("Manila", TimeZone.of("Asia/Manila")),
    Cites("Muscat", TimeZone.of("Asia/Muscat")),
    Cites("Nicosia", TimeZone.of("Asia/Nicosia")),
    Cites("Novokuznetsk", TimeZone.of("Asia/Novokuznetsk")),
    Cites("Novosibirsk", TimeZone.of("Asia/Novosibirsk")),
    Cites("Omsk", TimeZone.of("Asia/Omsk")),
    Cites("Oral", TimeZone.of("Asia/Oral")),
    Cites("Phnom Penh", TimeZone.of("Asia/Phnom_Penh")),
    Cites("Pontianak", TimeZone.of("Asia/Pontianak")),
    Cites("Pyongyang", TimeZone.of("Asia/Pyongyang")),
    Cites("Qatar", TimeZone.of("Asia/Qatar")),
    Cites("Qostanay", TimeZone.of("Asia/Qostanay")),
    Cites("Qyzylorda", TimeZone.of("Asia/Qyzylorda")),
    Cites("Rangoon", TimeZone.of("Asia/Rangoon")),
    Cites("Riyadh", TimeZone.of("Asia/Riyadh")),
    Cites("Saigon", TimeZone.of("Asia/Saigon")),
    Cites("Sakhalin", TimeZone.of("Asia/Sakhalin")),
    Cites("Samarkand", TimeZone.of("Asia/Samarkand")),
    Cites("Seoul", TimeZone.of("Asia/Seoul")),
    Cites("Shanghai", TimeZone.of("Asia/Shanghai")),
    Cites("Singapore", TimeZone.of("Asia/Singapore")),
    Cites("Srednekolymsk", TimeZone.of("Asia/Srednekolymsk")),
    Cites("Taipei", TimeZone.of("Asia/Taipei")),
    Cites("Tashkent", TimeZone.of("Asia/Tashkent")),
    Cites("Tbilisi", TimeZone.of("Asia/Tbilisi")),
    Cites("Tehran", TimeZone.of("Asia/Tehran")),
    Cites("Tel Aviv", TimeZone.of("Asia/Tel_Aviv")),
    Cites("Thimbu", TimeZone.of("Asia/Thimbu")),
    Cites("Thimphu", TimeZone.of("Asia/Thimphu")),
    Cites("Tokyo", TimeZone.of("Asia/Tokyo")),
    Cites("Tomsk", TimeZone.of("Asia/Tomsk")),
    Cites("Ujung Pandang", TimeZone.of("Asia/Ujung_Pandang")),
    Cites("Ulaanbaatar", TimeZone.of("Asia/Ulaanbaatar")),
    Cites("Ulan Bator", TimeZone.of("Asia/Ulan_Bator")),
    Cites("Urumqi", TimeZone.of("Asia/Urumqi")),
    Cites("Ust-Nera", TimeZone.of("Asia/Ust-Nera")),
    Cites("Vientiane", TimeZone.of("Asia/Vientiane")),
    Cites("Vladivostok", TimeZone.of("Asia/Vladivostok")),
    Cites("Yakutsk", TimeZone.of("Asia/Yakutsk")),
    Cites("Yangon", TimeZone.of("Asia/Yangon")),
    Cites("Yekaterinburg", TimeZone.of("Asia/Yekaterinburg")),
    Cites("Yerevan", TimeZone.of("Asia/Yerevan")),
    Cites("Azores", TimeZone.of("Atlantic/Azores")),
    Cites("Bermuda", TimeZone.of("Atlantic/Bermuda")),
    Cites("Canary", TimeZone.of("Atlantic/Canary")),
    Cites("Cape Verde", TimeZone.of("Atlantic/Cape_Verde")),
    Cites("Faeroe", TimeZone.of("Atlantic/Faeroe")),
    Cites("Faroe", TimeZone.of("Atlantic/Faroe")),
    Cites("Jan Mayen", TimeZone.of("Atlantic/Jan_Mayen")),
    Cites("Madeira", TimeZone.of("Atlantic/Madeira")),
    Cites("Reykjavik", TimeZone.of("Atlantic/Reykjavik")),
    Cites("South Georgia", TimeZone.of("Atlantic/South_Georgia")),
    Cites("St Helena", TimeZone.of("Atlantic/St_Helena")),
    Cites("Stanley", TimeZone.of("Atlantic/Stanley")),
    Cites("ACT", TimeZone.of("Australia/ACT")),
    Cites("Adelaide", TimeZone.of("Australia/Adelaide")),
    Cites("Brisbane", TimeZone.of("Australia/Brisbane")),
    Cites("Broken Hill", TimeZone.of("Australia/Broken_Hill")),
    Cites("Canberra", TimeZone.of("Australia/Canberra")),
    Cites("Currie", TimeZone.of("Australia/Currie")),
    Cites("Darwin", TimeZone.of("Australia/Darwin")),
    Cites("Eucla", TimeZone.of("Australia/Eucla")),
    Cites("Hobart", TimeZone.of("Australia/Hobart")),
    Cites("LHI", TimeZone.of("Australia/LHI")),
    Cites("Lindeman", TimeZone.of("Australia/Lindeman")),
    Cites("Lord Howe", TimeZone.of("Australia/Lord_Howe")),
    Cites("Melbourne", TimeZone.of("Australia/Melbourne")),
    Cites("NSW", TimeZone.of("Australia/NSW")),
    Cites("North", TimeZone.of("Australia/North")),
    Cites("Perth", TimeZone.of("Australia/Perth")),
    Cites("Queensland", TimeZone.of("Australia/Queensland")),
    Cites("South", TimeZone.of("Australia/South")),
    Cites("Sydney", TimeZone.of("Australia/Sydney")),
    Cites("Tasmania", TimeZone.of("Australia/Tasmania")),
    Cites("Victoria", TimeZone.of("Australia/Victoria")),
    Cites("West", TimeZone.of("Australia/West")),
    Cites("Yancowinna", TimeZone.of("Australia/Yancowinna")),
    Cites("Acre", TimeZone.of("Brazil/Acre")),
    Cites("DeNoronha", TimeZone.of("Brazil/DeNoronha")),
    Cites("East", TimeZone.of("Brazil/East")),
    Cites("West", TimeZone.of("Brazil/West")),
    Cites("Atlantic", TimeZone.of("Canada/Atlantic")),
    Cites("Central", TimeZone.of("Canada/Central")),
    Cites("Eastern", TimeZone.of("Canada/Eastern")),
    Cites("Mountain", TimeZone.of("Canada/Mountain")),
    Cites("Newfoundland", TimeZone.of("Canada/Newfoundland")),
    Cites("Pacific", TimeZone.of("Canada/Pacific")),
    Cites("Saskatchewan", TimeZone.of("Canada/Saskatchewan")),
    Cites("Yukon", TimeZone.of("Canada/Yukon")),
    Cites("Continental", TimeZone.of("Chile/Continental")),
    Cites("EasterIsland", TimeZone.of("Chile/EasterIsland")),
    Cites("GMT", TimeZone.of("Etc/GMT")),
    Cites("GMT+0", TimeZone.of("Etc/GMT+0")),
    Cites("GMT+1", TimeZone.of("Etc/GMT+1")),
    Cites("GMT+10", TimeZone.of("Etc/GMT+10")),
    Cites("GMT+11", TimeZone.of("Etc/GMT+11")),
    Cites("GMT+12", TimeZone.of("Etc/GMT+12")),
    Cites("GMT+2", TimeZone.of("Etc/GMT+2")),
    Cites("GMT+3", TimeZone.of("Etc/GMT+3")),
    Cites("GMT+4", TimeZone.of("Etc/GMT+4")),
    Cites("GMT+5", TimeZone.of("Etc/GMT+5")),
    Cites("GMT+6", TimeZone.of("Etc/GMT+6")),
    Cites("GMT+7", TimeZone.of("Etc/GMT+7")),
    Cites("GMT+8", TimeZone.of("Etc/GMT+8")),
    Cites("GMT+9", TimeZone.of("Etc/GMT+9")),
    Cites("GMT-0", TimeZone.of("Etc/GMT-0")),
    Cites("GMT-1", TimeZone.of("Etc/GMT-1")),
    Cites("GMT-10", TimeZone.of("Etc/GMT-10")),
    Cites("GMT-11", TimeZone.of("Etc/GMT-11")),
    Cites("GMT-12", TimeZone.of("Etc/GMT-12")),
    Cites("GMT-13", TimeZone.of("Etc/GMT-13")),
    Cites("GMT-14", TimeZone.of("Etc/GMT-14")),
    Cites("GMT-2", TimeZone.of("Etc/GMT-2")),
    Cites("GMT-3", TimeZone.of("Etc/GMT-3")),
    Cites("GMT-4", TimeZone.of("Etc/GMT-4")),
    Cites("GMT-5", TimeZone.of("Etc/GMT-5")),
    Cites("GMT-6", TimeZone.of("Etc/GMT-6")),
    Cites("GMT-7", TimeZone.of("Etc/GMT-7")),
    Cites("GMT-8", TimeZone.of("Etc/GMT-8")),
    Cites("GMT-9", TimeZone.of("Etc/GMT-9")),
    Cites("GMT0", TimeZone.of("Etc/GMT0")),
    Cites("Greenwich", TimeZone.of("Etc/Greenwich")),
    Cites("UCT", TimeZone.of("Etc/UCT")),
    Cites("UTC", TimeZone.of("Etc/UTC")),
    Cites("Universal", TimeZone.of("Etc/Universal")),
    Cites("Zulu", TimeZone.of("Etc/Zulu")),
    Cites("Amsterdam", TimeZone.of("Europe/Amsterdam")),
    Cites("Andorra", TimeZone.of("Europe/Andorra")),
    Cites("Astrakhan", TimeZone.of("Europe/Astrakhan")),
    Cites("Athens", TimeZone.of("Europe/Athens")),
    Cites("Belfast", TimeZone.of("Europe/Belfast")),
    Cites("Belgrade", TimeZone.of("Europe/Belgrade")),
    Cites("Berlin", TimeZone.of("Europe/Berlin")),
    Cites("Bratislava", TimeZone.of("Europe/Bratislava")),
    Cites("Brussels", TimeZone.of("Europe/Brussels")),
    Cites("Bucharest", TimeZone.of("Europe/Bucharest")),
    Cites("Budapest", TimeZone.of("Europe/Budapest")),
    Cites("Busingen", TimeZone.of("Europe/Busingen")),
    Cites("Chisinau", TimeZone.of("Europe/Chisinau")),
    Cites("Copenhagen", TimeZone.of("Europe/Copenhagen")),
    Cites("Dublin", TimeZone.of("Europe/Dublin")),
    Cites("Gibraltar", TimeZone.of("Europe/Gibraltar")),
    Cites("Guernsey", TimeZone.of("Europe/Guernsey")),
    Cites("Helsinki", TimeZone.of("Europe/Helsinki")),
    Cites("Isle of Man", TimeZone.of("Europe/Isle_of_Man")),
    Cites("Istanbul", TimeZone.of("Europe/Istanbul")),
    Cites("Jersey", TimeZone.of("Europe/Jersey")),
    Cites("Kaliningrad", TimeZone.of("Europe/Kaliningrad")),
    Cites("Kiev", TimeZone.of("Europe/Kiev")),
    Cites("Kirov", TimeZone.of("Europe/Kirov")),
    Cites("Kyiv", TimeZone.of("Europe/Kyiv")),
    Cites("Lisbon", TimeZone.of("Europe/Lisbon")),
    Cites("Ljubljana", TimeZone.of("Europe/Ljubljana")),
    Cites("London", TimeZone.of("Europe/London")),
    Cites("Luxembourg", TimeZone.of("Europe/Luxembourg")),
    Cites("Madrid", TimeZone.of("Europe/Madrid")),
    Cites("Malta", TimeZone.of("Europe/Malta")),
    Cites("Mariehamn", TimeZone.of("Europe/Mariehamn")),
    Cites("Minsk", TimeZone.of("Europe/Minsk")),
    Cites("Monaco", TimeZone.of("Europe/Monaco")),
    Cites("Moscow", TimeZone.of("Europe/Moscow")),
    Cites("Nicosia", TimeZone.of("Europe/Nicosia")),
    Cites("Oslo", TimeZone.of("Europe/Oslo")),
    Cites("Paris", TimeZone.of("Europe/Paris")),
    Cites("Podgorica", TimeZone.of("Europe/Podgorica")),
    Cites("Prague", TimeZone.of("Europe/Prague")),
    Cites("Riga", TimeZone.of("Europe/Riga")),
    Cites("Rome", TimeZone.of("Europe/Rome")),
    Cites("Samara", TimeZone.of("Europe/Samara")),
    Cites("San Marino", TimeZone.of("Europe/San_Marino")),
    Cites("Sarajevo", TimeZone.of("Europe/Sarajevo")),
    Cites("Saratov", TimeZone.of("Europe/Saratov")),
    Cites("Simferopol", TimeZone.of("Europe/Simferopol")),
    Cites("Skopje", TimeZone.of("Europe/Skopje")),
    Cites("Sofia", TimeZone.of("Europe/Sofia")),
    Cites("Stockholm", TimeZone.of("Europe/Stockholm")),
    Cites("Tallinn", TimeZone.of("Europe/Tallinn")),
    Cites("Tirane", TimeZone.of("Europe/Tirane")),
    Cites("Tiraspol", TimeZone.of("Europe/Tiraspol")),
    Cites("Ulyanovsk", TimeZone.of("Europe/Ulyanovsk")),
    Cites("Uzhgorod", TimeZone.of("Europe/Uzhgorod")),
    Cites("Vaduz", TimeZone.of("Europe/Vaduz")),
    Cites("Vatican", TimeZone.of("Europe/Vatican")),
    Cites("Vienna", TimeZone.of("Europe/Vienna")),
    Cites("Vilnius", TimeZone.of("Europe/Vilnius")),
    Cites("Volgograd", TimeZone.of("Europe/Volgograd")),
    Cites("Warsaw", TimeZone.of("Europe/Warsaw")),
    Cites("Zagreb", TimeZone.of("Europe/Zagreb")),
    Cites("Zaporozhye", TimeZone.of("Europe/Zaporozhye")),
    Cites("Zurich", TimeZone.of("Europe/Zurich")),
    Cites("Antananarivo", TimeZone.of("Indian/Antananarivo")),
    Cites("Chagos", TimeZone.of("Indian/Chagos")),
    Cites("Christmas", TimeZone.of("Indian/Christmas")),
    Cites("Cocos", TimeZone.of("Indian/Cocos")),
    Cites("Comoro", TimeZone.of("Indian/Comoro")),
    Cites("Kerguelen", TimeZone.of("Indian/Kerguelen")),
    Cites("Mahe", TimeZone.of("Indian/Mahe")),
    Cites("Maldives", TimeZone.of("Indian/Maldives")),
    Cites("Mauritius", TimeZone.of("Indian/Mauritius")),
    Cites("Mayotte", TimeZone.of("Indian/Mayotte")),
    Cites("Reunion", TimeZone.of("Indian/Reunion")),
    Cites("BajaNorte", TimeZone.of("Mexico/BajaNorte")),
    Cites("BajaSur", TimeZone.of("Mexico/BajaSur")),
    Cites("General", TimeZone.of("Mexico/General")),
    Cites("Apia", TimeZone.of("Pacific/Apia")),
    Cites("Auckland", TimeZone.of("Pacific/Auckland")),
    Cites("Bougainville", TimeZone.of("Pacific/Bougainville")),
    Cites("Chatham", TimeZone.of("Pacific/Chatham")),
    Cites("Chuuk", TimeZone.of("Pacific/Chuuk")),
    Cites("Easter", TimeZone.of("Pacific/Easter")),
    Cites("Efate", TimeZone.of("Pacific/Efate")),
    Cites("Enderbury", TimeZone.of("Pacific/Enderbury")),
    Cites("Fakaofo", TimeZone.of("Pacific/Fakaofo")),
    Cites("Fiji", TimeZone.of("Pacific/Fiji")),
    Cites("Funafuti", TimeZone.of("Pacific/Funafuti")),
    Cites("Galapagos", TimeZone.of("Pacific/Galapagos")),
    Cites("Gambier", TimeZone.of("Pacific/Gambier")),
    Cites("Guadalcanal", TimeZone.of("Pacific/Guadalcanal")),
    Cites("Guam", TimeZone.of("Pacific/Guam")),
    Cites("Honolulu", TimeZone.of("Pacific/Honolulu")),
    Cites("Johnston", TimeZone.of("Pacific/Johnston")),
    Cites("Kanton", TimeZone.of("Pacific/Kanton")),
    Cites("Kiritimati", TimeZone.of("Pacific/Kiritimati")),
    Cites("Kosrae", TimeZone.of("Pacific/Kosrae")),
    Cites("Kwajalein", TimeZone.of("Pacific/Kwajalein")),
    Cites("Majuro", TimeZone.of("Pacific/Majuro")),
    Cites("Marquesas", TimeZone.of("Pacific/Marquesas")),
    Cites("Midway", TimeZone.of("Pacific/Midway")),
    Cites("Nauru", TimeZone.of("Pacific/Nauru")),
    Cites("Niue", TimeZone.of("Pacific/Niue")),
    Cites("Norfolk", TimeZone.of("Pacific/Norfolk")),
    Cites("Noumea", TimeZone.of("Pacific/Noumea")),
    Cites("Pago Pago", TimeZone.of("Pacific/Pago_Pago")),
    Cites("Palau", TimeZone.of("Pacific/Palau")),
    Cites("Pitcairn", TimeZone.of("Pacific/Pitcairn")),
    Cites("Pohnpei", TimeZone.of("Pacific/Pohnpei")),
    Cites("Ponape", TimeZone.of("Pacific/Ponape")),
    Cites("Port Moresby", TimeZone.of("Pacific/Port_Moresby")),
    Cites("Rarotonga", TimeZone.of("Pacific/Rarotonga")),
    Cites("Saipan", TimeZone.of("Pacific/Saipan")),
    Cites("Samoa", TimeZone.of("Pacific/Samoa")),
    Cites("Tahiti", TimeZone.of("Pacific/Tahiti")),
    Cites("Tarawa", TimeZone.of("Pacific/Tarawa")),
    Cites("Tongatapu", TimeZone.of("Pacific/Tongatapu")),
    Cites("Truk", TimeZone.of("Pacific/Truk")),
    Cites("Wake", TimeZone.of("Pacific/Wake")),
    Cites("Wallis", TimeZone.of("Pacific/Wallis")),
    Cites("Yap", TimeZone.of("Pacific/Yap")),
    Cites("Alaska", TimeZone.of("US/Alaska")),
    Cites("Aleutian", TimeZone.of("US/Aleutian")),
    Cites("Arizona", TimeZone.of("US/Arizona")),
    Cites("Central", TimeZone.of("US/Central")),
    Cites("East-Indiana", TimeZone.of("US/East-Indiana")),
    Cites("Eastern", TimeZone.of("US/Eastern")),
    Cites("Hawaii", TimeZone.of("US/Hawaii")),
    Cites("Indiana-Starke", TimeZone.of("US/Indiana-Starke")),
    Cites("Michigan", TimeZone.of("US/Michigan")),
    Cites("Mountain", TimeZone.of("US/Mountain")),
    Cites("Pacific", TimeZone.of("US/Pacific")),
    Cites("Samoa", TimeZone.of("US/Samoa"))
)
